name: btelnyy-smputilities
main: me.btelnyy.smputilities.SmpUtilities
version: ${project.version}
api-version: 1.21
commands:
  transferxp:
    description: Transfer XP!
    usage: /transferxp <player> <levels>
    permissions: btelnyy.command.transferxp